### ISSUE TITLE
Energy waste - curtailment of volatile producers in CO2 optimisation

### ISSUE THREAD

**Issue by johburger** [SES-fortiss/SmartGridCoSimulation#160]
When optimising for CO2, curtailment of volatile producers is possible and will be done by MPC. When enough volatile (free) energy is available and the MPC horizon cannot see far enough to detect a decreasing free energy, the optimiser does not charge a storage but curtails the volatile producer. This can be seen in the screenshot where PV production, storage SOC and charging/discharging powers are depicted:
![Screenshot 2021-04-11 at 19 00 41](https://user-images.githubusercontent.com/63449992/114895674-fcecaf80-9e0f-11eb-9805-cf60328b5062.png)
We could implement a negative CO2-price for storages that tells the MPC to better charge it than waste it. Another consideration might be, that the MPC could also sell the free excess energy, even though that is not optimal from a long term perspective as the energy charged to the storage can be used later.

**Comment by bytschkow** [comment]
I think both ideas are good. Maybe we can discuss it shortly and vote which is the preferred solution for our use case.

**Comment by JanAxelMayer** [comment]
Selling free excess energy should be the normal (EEG) case, right? Why doesn't the optimizer do that? Because it is CO2-neutral?
Storing the energy would be the better option, as it can be either used or fed into the grid later.

But, I think we have to reward both actions with a negative CO2-price (elsewise it would curtail the volatile producer when the storage is full). Question remains, which one should have a higher incentive? I would vote for the storage.

**Comment by thomaslicklederer** [comment]
Yes, you are right, Jan. The optimizer doesn't do that, because it's CO2-neutral. In case the foresight doesn't go far enough to see a lack of energy (so within the whole horizon there is excess energy available via PV), then the curtailment of PV, storing the excess PV-energy or selling it are equal solutions from the objective function point of view. It's just due to numerical properties of the solver then, which of this equal solutions is chosen. In our case the solver tends to curtail the PV production.

Although I don't like heuristics normally, I don't have a good and fast alternative solution to heuristics here. So I agree that a good and fast solution here is to reward storing and selling with negative CO2-prices, but very low absolute values. sth like -0.00010 and -0.00012. I also agree with Jan to give the price with the higher abolute value (higher incentive) to storing.
